Run Changesets as linter (#579)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,8 +17,24 @@ jobs:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 ## Needed for Changesets to find `main` branch
 
       - uses: ./.github/actions/warm-up-repo
+
+      - name: Run yarn lint:changeset
+        if: ${{ success() || failure() }}
+        run: |
+          git pull --force --no-tags origin main:main ## https://github.com/changesets/changesets/issues/517
+          if ! yarn lint:changeset; then
+            echo ''
+            echo ''
+            echo 'ℹ️ ℹ️ ℹ️'
+            echo 'Please fix the above errors locally for the check to pass.'
+            echo 'If you don’t see them, try merging target branch into yours.'
+            echo 'ℹ️ ℹ️ ℹ️'
+            exit 1
+          fi
 
       - name: Run yarn lint:dependency-version-consistency
         if: ${{ success() || failure() }}
